### ISSUE TITLE
Инконсистентни urls.py

### ISSUE THREAD

**Issue by vladimiroff** [Hackfmi/Diaphanum#1]
Нека някой от бекенда се нагърби с това да фикнсе URL-ите в целия проект.

Задачи:
1. Да се разкарат всички коментари
2. Всеки app да има свой urls.py, който да бъде include-ван в основния (подобно на този от admin частта).
3. Всеки include да дефинира и namespace
4. Всеки url трябва да завършва с /
5. Всеки url из целия проект (темплейти, view-та, тестове) да използва reverse `namespace:url_name`

Който реши да го прави това, да отвори нов бранч от мастър.

**Comment by hhursev** [comment]
мм я погледни това https://github.com/Hackfmi/Diaphanum/blob/urls_fix/hackfmi/urls.py + другите url
не знам как точно да процедирам с homepage-а + /members/login за логин url ок ли е?

П.П. в почти никое view нямаме ползвано reverse или редирект (все още).. същото се отнася и за тестовете, само трябваше някои от тях да се сменят поради промяна в url адресите

**Comment by vladimiroff** [comment]
- идеално е така. homepage-а си нацелил как трябва се опише (т.е. коментарът след него отпада).
- /members/login/ си е супер
