### ISSUE TITLE
Protocols add problems.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [Hackfmi/Diaphanum#10]
Следните полета не работят и не ги виждам в тестовете. През формата не мога да ги добавя но през админа мога.
excused - другите 2 полета работят това не иска.

И полетата за гласуване на дневния ред (не на отделните точки) 
voted_for итн.
Ще ми трябва и едно поле с допълнителна информация за гласуването на самия ред.

**Comment by victoria92** [comment]
Вече ги имаш, добавих ги и в тестовете, направих отсъстващите и извинените незадължителни

**Comment by Ivaylo-Bachvarov** [comment]
Мерсии :cat:
