### ISSUE TITLE
DoesNotExist at /projects/archive/review/versions/11/

### ISSUE THREAD

**Issue by RadoRado** [Hackfmi/Diaphanum#11]
Как стихнах до това - 
1. Промених статусът на проекта на върнат за корекции
2. Нанесох му корекции
3. Отидох да му видя версиите от публичната версия
4. Ударих този екран (Специално проверих - в базата го има ;))

![image](https://f.cloud.github.com/assets/387867/1110365/1bed9ec2-1992-11e3-9de2-62388cec1f82.png)

**Comment by victoria92** [comment]
Проблемът е, че това с версиите е останало в backend-branch и просто трябва да се добави в master. Ако ги merge-неш би трябвало да стане

**Comment by RadoRado** [comment]
@victoria92 Merge-нато е, другите версии работят ;)
Само и специално за този Index гърми
