### ISSUE TITLE
protocols/archive backend support needed.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [Hackfmi/Diaphanum#12]
Ще ми трябва малко backend помощ за търсачката, която съм направил за протоколите. Филтриране по институция и дати, както и странициране. В frondend branch-a e. listing.html  е файла. Ако някой има време може да удари едно рамо.

Мерси. :panda_face: :panda_face: :panda_face:

**Comment by victoria92** [comment]
Аз мога да ти ударя едно рамо, но ще е чак довечера, ако не си намериш ентусиаст дотогава.

**Comment by Ivaylo-Bachvarov** [comment]
Не е спешно :+1:

**Comment by victoria92** [comment]
В момента го има качено в backend, но се оказа, че повечето тестове на проектите са сгрешени и ще трябва да ги оправя, за да не прецакат master
