### ISSUE TITLE
[Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by RadoRado** [Hackfmi/Diaphanum#17]
Опитах се да submit-на нов проект, докато тествах за multiple file upload и при POST ми даде следната грешка:
![image](https://f.cloud.github.com/assets/387867/1252600/36855f72-2b4e-11e3-96f4-0ad0f1d5bc92.png)

До колкото виждам е проблем при изпращането на email.
@victoria92 трябва ли да си инсталирам нещо допълнително, като SMTP сървър например, към Django, за да тръгне локално ?

**Comment by Ivaylo-Bachvarov** [comment]
Аз не съм имал проблем, но сигурно по подразбиране имам инсталирано това което трябва :monkey_face:

**Comment by RadoRado** [comment]
Да, хубаво е да спомена, че съм под Windows :)

**Comment by victoria92** [comment]
И аз съм по Window, но не получавам подобна грешка

**Comment by vladimiroff** [comment]
Я си сетни друг `EmailBackend`. Нямаш нужда от реален мейл сървър на dev машина. Я набий тези в `local_settings.py` и кажи какво се случва

``` python
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = 'C:\Users\...\Desktop' 
```
