### ISSUE TITLE
Правописни грешки в проектния формуляр

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#22]
![screenshot from 2013-12-12 00 45 02](https://f.cloud.github.com/assets/4212280/1728900/d7c28b86-62b6-11e3-8e0c-73a57e075a4a.png)

**Comment by Ivaylo-Bachvarov** [comment]
На следващия deploy ще ги оправя и двете. Мерси много за reporta.

**Comment by Ivaylo-Bachvarov** [comment]
Готово, в следващия deploy ще видиш промяната.
