### ISSUE TITLE
В print версията на проект липсват данните на СС

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#23]
![screenshot from 2013-12-12 00 55 46](https://f.cloud.github.com/assets/4212280/1729013/84b78c00-62b8-11e3-8477-79104faf2b5f.png)
![screenshot from 2013-12-12 00 57 25](https://f.cloud.github.com/assets/4212280/1729014/84b9af58-62b8-11e3-90aa-f47b3a347c85.png)

Също така едно предложение за рамките м/у полетата в проекта да са с малко по-тъмен нюанс, защото при печат почти не се виждат.

**Comment by Ivaylo-Bachvarov** [comment]
Оправи си принтера. :-D И за това ще се погрижа. Мерси за репорта.

**Comment by simeonbg** [comment]
Не е от принтера. Линиите са бледи, все пак проекта е печатан на 3 различни принтера и на трите са бледи. Днес гледах проекта, отпечатан от принтера на СС. Пък Дани е на същото мнение :D

**Comment by Ivaylo-Bachvarov** [comment]
Agree!

**Comment by Ivaylo-Bachvarov** [comment]
Готово :-)

**Comment by simeonbg** [comment]
Верно ли си го сложил като image. Чакай тогава да го пипна малко, щото не искам грозотии от Word в Diaphanum-а.

**Comment by simeonbg** [comment]
Чакам одобрение за една нова визия и ще я пратя да я замениш. ;)

**Comment by simeonbg** [comment]
Иво кажи в какъв вариант искаш новият header - tiff или png. Всъщност няма значение, тъй като няма как да ти кача tiff-а.
![templateforssprojects](https://f.cloud.github.com/assets/4212280/1779934/1c9ebf5e-685c-11e3-9a82-174c4ce20d39.png)

Само му сложи някакъв border.
Също така в print варианта махни бутона за принтиране. :)

**Comment by simeonbg** [comment]
Има някакъв проблем, че при принтиране не си проверява автоматично размерите и отрязва текст или оставя прекалено много празно място. Също може би е хубаво да си нормира така полетата, че цяло group-че да може да се принтира заедно на една страница.

**Comment by Ivaylo-Bachvarov** [comment]
Ще го погледна. При мен размерите са добре, ще тествам на други машини и принтери.
