### ISSUE TITLE
Някакъв проблем с извеждането на датата на подаване на проекта

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#24]
![screenshot from 2013-12-12 01 10 07](https://f.cloud.github.com/assets/4212280/1729078/9308712e-62b9-11e3-9447-e9cdea68a04c.png)

Убеден съм, че това не е датата на подаване на проекта.
На 23.11. май съм пускал първия проект.
Вторият проект съм го пуснал на 25 или 26 ноември.
След това са пуснати още 2 проекта от колегата Мишо Станев от Биологическия факултет, които със сигурност са след тези дати, като последният е от последните няколко дни.

Не знам дали извежда датата на добавяне на първия проект или датата на регистриране на първия човек с проект.

**Comment by Ivaylo-Bachvarov** [comment]
@victoria92 :panda_face: Ще го прегледаме на всяка цена.

**Comment by victoria92** [comment]
Мисля, че знам къде е проблемът, но какво ще правим с вече подадените проекти? Лесно ще го оправим за следващите, но тези не знам @Ivaylo-Bachvarov

**Comment by Ivaylo-Bachvarov** [comment]
Ако проблема е, че сме запазили кофти данни в базата, ще е гадно. Но пак ще го оправим :computer: :monkey:

**Comment by simeonbg** [comment]
Вики, извинявай за забавянето.
1. мой проект - 23.11
2. мой проект - 25.11
1. проект на Мишо - 05.12
2. проект на Мишо - 06.12

**Comment by Ivaylo-Bachvarov** [comment]
Оправени са датите на първите 4 проекта. :panda_face: Сменихме датите с реалните!
