### ISSUE TITLE
Отварянето на качени файлове към проекти

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#29]
Не може да се отвори прикачен файл в проекти.

До четвъртък вечерта, също май не можеше да се качват файлове, но виждам, че е било оправено. Оправете да могат да се разглеждат качени файлове.

**Comment by Ivaylo-Bachvarov** [comment]
Сега ще го погледна :panda_face:

**Comment by Ivaylo-Bachvarov** [comment]
Готово вече качените файлове могат да се гледат. Проблема беше в nginx config. :computer:
