### ISSUE TITLE
Подреждане на проектите в търсачката

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#30]
Хубаво е според мен проектите да са подредени хронологично, а не по реда на редакцията им.

Предложението ми да се подредят най-отгоре одобрени проекти, по реда им на подаване - т.е. първото им качване (входиране).

След това, неразгледаните проекти да бъдат отново по реда им на постъпване, а не по реда на редактиране.

**Comment by Ivaylo-Bachvarov** [comment]
@simeonbg В момента както трябва ли е?

**Comment by simeonbg** [comment]
Дам. (happy)
