### ISSUE TITLE
Печат на проектите

### ISSUE THREAD

**Issue by simeonbg** [Hackfmi/Diaphanum#31]
![2014-03-18_181610](https://f.cloud.github.com/assets/4212280/2490315/15b42b22-b1a2-11e3-895e-df5fe4c91315.jpg)
Това е новолото лого, което да е отгоре на проектите.

Също така, да се разгледа изцяло версията за принтиране, тъй като се изяжда текст и той не се вижда при печат. За да замажа това, трябваше да слагам празни редове. Също така е хубаво всеки textbox-а да е заедно с label-а си на една страница, а не да се разделя.

**Comment by Ivaylo-Bachvarov** [comment]
Смених header-a. 

Не разбирам, кой текст не се вижда при принтиране. При мен всичко се вижда.

**Comment by simeonbg** [comment]
Eла, в зала 100, да ти ги отпечатам и да видиш.

**Comment by simeonbg** [comment]
@Ivaylo-Bachvarov, свий малко логото, тъй като при печат се отрязва част от него.

**Comment by simeonbg** [comment]
![image](https://cloud.githubusercontent.com/assets/4212280/2558405/853bdc3e-b746-11e3-8ea1-7d6270733972.JPG)
![image0001](https://cloud.githubusercontent.com/assets/4212280/2558406/853cdaf8-b746-11e3-978f-9b334ddfd4ae.JPG)
@Ivaylo-Bachvarov виж как се отрязва логото най-отгоре, както и как се печатат полета.
Виж като се пуска за печат да излиза label-а + textbox-а на една страница.
Също при печат, не трябва да да се отпечатва бутон за принтиране.

**Comment by Ivaylo-Bachvarov** [comment]
@simeonbg Виш сега как е. Това с Label-a мисля, че няма как да се направи. Иначе вече принтирането трябва да е доста по-добре. Пробвай и дай feedback.

**Comment by simeonbg** [comment]
Муцка, Label-а, ако ти го пратя по-свит като изображение, дали няма да стане.
