### ISSUE TITLE
Back-end error handling.

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [Hackfmi/Diaphanum#6]
Как можем да процедираме с прихващането на грешки от backend-а, за да не стават неща от сорта на:
![te](https://f.cloud.github.com/assets/1764612/1063758/d99d65dc-12e5-11e3-9e15-efcc9d0dda13.png)

**Comment by Ivaylo-Bachvarov** [comment]
ping @hhursev

**Comment by hhursev** [comment]
ооп.. еми в div class="alert alert-danger internelError".. ей сега ще ти направя една проверка дали username-а е объркан или паролата. в кой бранч я искаш ?

**Comment by Ivaylo-Bachvarov** [comment]
master :smile_cat: То проверка реално има само съобщението е грозновато.

**Comment by RadoRado** [comment]
@Ivaylo-Bachvarov @hhursev аз съм го оправим това, например за редактирането на проектите.
Може да погледнеш файла form_error.html, който е в базовите templates

Там слагам имената на field-овете и после го обхождам с този JS:

```
  $(".errorFieldName").each(function() {
    var labelName = $("input[name=" + $(this).html() + "]")
                      .closest(".control-group")
                      .find("label.control-label")
                      .html();
    console.log(labelName);

    $(this).html(labelName);
  });
```

И ги сменям с това, което дефакто има за Label на съответният елемент ;)

**Comment by RadoRado** [comment]
Сега видях commit-ите на @hhursev и май няма нужда от това, което съм писал за проектните форми ;) Всичко е OK :cat:
