### ISSUE TITLE
form_error.html не работи за protocols/add.html

### ISSUE THREAD

**Issue by Ivaylo-Bachvarov** [Hackfmi/Diaphanum#8]
form_error.html прихваща грешките така : https://github.com/Hackfmi/Diaphanum/blob/master/hackfmi/templates/form_error.html 
а в protocols/add.html грешките се прихващат така:

{% if topic_form.errors %}

<div class="alert alert-danger internel-error">
  <strong>Грешка! </strong>
  {{ topic_form.errors }}
</div>

{% endif %}

{% if protocol_form %}
{{ protocol_form.errors }}
{% endif %}

{% if institution_form %}
{{ institution_form.errors }}
{% endif %}

И когато include-вам form_error.html не прихваща грешките. Някой има ли елегантно решение за проблема?

**Comment by RadoRado** [comment]
Защо има 3 различни форми ? (topic_form, protocol_form и institution_form)

Иначе не прихваща от form_errors.html, защото там е написано с form.errors, а не protocol_form.errors
Написах файлът, за да не се повтаря при add / edit на проекти, но като гледам не съм го сложил на най-правилното място (при основните templates) и по-скоро трябва да го преместя при проектите ;)

**Comment by Ivaylo-Bachvarov** [comment]
Да реших, че този ще е за всички форми защото е в hackfmi/templates/
